<a href="https://colab.research.google.com/github/leesangh92/homework/blob/main/(21_5_20)hw_%EC%88%98%EC%A0%95%ED%95%84%EC%9A%94.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

===> 오후 도전


data.go.kr
검색어 : 서울시 구별 인구수

파일 다운로드 
25개구 전입남자 전입여자 전출남자 전출여자

pop.csv 저장
colab으로 업로드 
DataFrame으로 가져오기

총전입, 총전출을 구해 새로운 column을 만든다

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pop1 = pd.read_csv('/content/sample_data/report.csv')

In [ ]:
pop1

         기간    자치구         총이동       총이동.1  ... 시ㆍ도간이동.5     순이동   순이동.1   순이동.2
0        기간    자치구  총전입(①+②+④)  총전입(①+②+④)  ...    전출(⑤)     순이동     순이동     순이동
1        기간    자치구  총전입(①+②+④)  총전입(①+②+④)  ...    전출(⑤)     순이동     순이동     순이동
2        기간    자치구          소계          남자  ...       여자       계      남자      여자
3   2021.03  서울특별시     151,617      73,389  ...   28,887  -6,216  -4,453  -1,763
4   2021.03    종로구       2,644       1,266  ...      444     -53     -87      34
5   2021.03     중구       1,966         949  ...      352    -178    -126     -52
6   2021.03    용산구       4,462       2,111  ...      674     580     169     411
7   2021.03    성동구       4,656       2,282  ...      800    -385    -293     -92
8   2021.03    광진구       5,432       2,551  ...    1,093    -395    -224    -171
9   2021.03   동대문구       5,640       2,802  ...    1,007      96      36      60
10  2021.03    중랑구       5,129       2,534  ...    1,043    -523    -326    -197
11  2021.03    성북구       6,761       3,180  ...    1,162    -188    -206      18
12  2021.03    강북구       3,802       1,865  ...      698    -484    -256    -228
13  2021.03    도봉구       3,754       1,831  ...      777    -565    -291    -274
14  2021.03    노원구       6,372       3,075  ...    1,301    -677    -404    -273
15  2021.03    은평구       6,021       2,859  ...    1,425    -630    -372    -258
16  2021.03   서대문구       4,930       2,252  ...      920    -160    -203      43
17  2021.03    마포구       6,599       3,104  ...    1,158    -187     -58    -129
18  2021.03    양천구       6,162       3,048  ...      987    -240    -208     -32
19  2021.03    강서구       9,737       4,708  ...    1,732     246     -25     271
20  2021.03    구로구       5,175       2,591  ...    1,231    -246     -94    -152
21  2021.03    금천구       3,388       1,732  ...      784     -52     -34     -18
22  2021.03   영등포구       6,206       3,027  ...    1,190     -14    -102      88
23  2021.03    동작구       7,245       3,504  ...    1,270     389     178     211
24  2021.03    관악구       9,971       5,001  ...    1,991    -277    -192     -85
25  2021.03    서초구       6,102       2,914  ...    1,190  -1,025    -478    -547
26  2021.03    강남구       8,868       4,298  ...    1,712  -1,277    -656    -621
27  2021.03    송파구      10,653       5,079  ...    2,496  -2,090  -1,151    -939
28  2021.03    강동구       9,942       4,826  ...    1,450   2,119     950   1,169

[29 rows x 26 columns]

In [ ]:
pop1.head(5)

        기간    자치구         총이동       총이동.1  ... 시ㆍ도간이동.5     순이동   순이동.1   순이동.2
0       기간    자치구  총전입(①+②+④)  총전입(①+②+④)  ...    전출(⑤)     순이동     순이동     순이동
1       기간    자치구  총전입(①+②+④)  총전입(①+②+④)  ...    전출(⑤)     순이동     순이동     순이동
2       기간    자치구          소계          남자  ...       여자       계      남자      여자
3  2021.03  서울특별시     151,617      73,389  ...   28,887  -6,216  -4,453  -1,763
4  2021.03    종로구       2,644       1,266  ...      444     -53     -87      34

[5 rows x 26 columns]

전입남자 전입여자 전출남자 전출여자

pop.csv 저장 colab으로 업로드 DataFrame으로 가져오기

In [ ]:
pop = pop1.loc[:,['기간', '자치구', '총이동', '총이동.1', '총이동.2', '총이동.4', '총이동.5']]

In [ ]:
pop.columns(['기간'], ['자치구'], ['총이동'], ['전입남자']. ['전입여자'], ['전출남자'], ['전출여자'])

SyntaxError: ignored

In [ ]:
pop

         기간    자치구         총이동       총이동.1       총이동.2       총이동.4       총이동.5
0        기간    자치구  총전입(①+②+④)  총전입(①+②+④)  총전입(①+②+④)  총전출(①+③+⑤)  총전출(①+③+⑤)
1        기간    자치구  총전입(①+②+④)  총전입(①+②+④)  총전입(①+②+④)  총전출(①+③+⑤)  총전출(①+③+⑤)
2        기간    자치구          소계          남자          여자          남자          여자
3   2021.03  서울특별시     151,617      73,389      78,228      77,842      79,991
4   2021.03    종로구       2,644       1,266       1,378       1,353       1,344
5   2021.03     중구       1,966         949       1,017       1,075       1,069
6   2021.03    용산구       4,462       2,111       2,351       1,942       1,940
7   2021.03    성동구       4,656       2,282       2,374       2,575       2,466
8   2021.03    광진구       5,432       2,551       2,881       2,775       3,052
9   2021.03   동대문구       5,640       2,802       2,838       2,766       2,778
10  2021.03    중랑구       5,129       2,534       2,595       2,860       2,792
11  2021.03    성북구       6,761       3,180       3,581       3,386       3,563
12  2021.03    강북구       3,802       1,865       1,937       2,121       2,165
13  2021.03    도봉구       3,754       1,831       1,923       2,122       2,197
14  2021.03    노원구       6,372       3,075       3,297       3,479       3,570
15  2021.03    은평구       6,021       2,859       3,162       3,231       3,420
16  2021.03   서대문구       4,930       2,252       2,678       2,455       2,635
17  2021.03    마포구       6,599       3,104       3,495       3,162       3,624
18  2021.03    양천구       6,162       3,048       3,114       3,256       3,146
19  2021.03    강서구       9,737       4,708       5,029       4,733       4,758
20  2021.03    구로구       5,175       2,591       2,584       2,685       2,736
21  2021.03    금천구       3,388       1,732       1,656       1,766       1,674
22  2021.03   영등포구       6,206       3,027       3,179       3,129       3,091
23  2021.03    동작구       7,245       3,504       3,741       3,326       3,530
24  2021.03    관악구       9,971       5,001       4,970       5,193       5,055
25  2021.03    서초구       6,102       2,914       3,188       3,392       3,735
26  2021.03    강남구       8,868       4,298       4,570       4,954       5,191
27  2021.03    송파구      10,653       5,079       5,574       6,230       6,513
28  2021.03    강동구       9,942       4,826       5,116       3,876       3,947

In [ ]:
type(pop)

pandas.core.frame.DataFrame

In [ ]:
pop.head(5)

        기간    자치구         총이동       총이동.1       총이동.2       총이동.4       총이동.5
0       기간    자치구  총전입(①+②+④)  총전입(①+②+④)  총전입(①+②+④)  총전출(①+③+⑤)  총전출(①+③+⑤)
1       기간    자치구  총전입(①+②+④)  총전입(①+②+④)  총전입(①+②+④)  총전출(①+③+⑤)  총전출(①+③+⑤)
2       기간    자치구          소계          남자          여자          남자          여자
3  2021.03  서울특별시     151,617      73,389      78,228      77,842      79,991
4  2021.03    종로구       2,644       1,266       1,378       1,353       1,344

총전입, 총전출을 구해 새로운 column을 만든다

In [ ]:
pop['move_in'] = pop.loc[3:, ['총이동1']].sum(axis = 1) + pop.loc[3: ,['총이동4']].sum(axis = 1)

KeyError: ignored

In [ ]:
man_in = pop['총이동1'].sum(axis = 1)

KeyError: ignored

In [ ]:
man_out = pop.loc[3:, ['총이동.4']]

In [ ]:
woman_in = pop.loc[3:, ['총이동.2']]

In [ ]:
woman_out = pop.loc[3:, ['총이동.5']]

In [ ]:
man_in

In [ ]:
man_out

In [ ]:
woman_in

In [ ]:
woman_out

In [ ]:
move_in = man_in + woman_in

In [ ]:
move_out =

In [ ]:
move_in